/**
 * The preset table, handed to the settings page as a package-local client chunk.
 *
 * The browser cannot read the harness model catalog on its own:
 * `@earendil-works/pi-ai` is a Host dependency and a client bundle's `require`
 * only resolves platform seeds. The plugin-visible wires do not carry a table
 * this size either — a Session projection baseline re-sends every value on every
 * frame and for every listed Session, and a custom Remote namespace needs
 * generated Typert contributions, which only the assembly can add.
 *
 * A package-local client chunk is the sanctioned way for a plugin to ship extra
 * browser code: the client asks for it with `require.async("./client.rates.js")`
 * and the Host serves it from `/plugins/<id>/client.rates.js?rev=<client.js rev>`.
 * So the Host half materializes the table as that chunk and the settings page
 * loads it on demand — the cost is paid only when someone opens the page, and
 * never on the Session hot path.
 *
 * That URL carries the *client entry's* artifact revision, which is a metadata
 * hash of `lib/client.js` (mtime, ctime, size). Regenerating the table therefore
 * has to move that metadata, which is exactly the change the client-HMR watcher
 * already reads as "this bundle was rebuilt". Only a changed table touches it.
 *
 * @module dsh-session-cost/rates-chunk
 */
import { readFileSync, utimesSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { catalogGeneratedAt, catalogPresets, createPriceLookup, presetRoutes } from "./presets.js";

/** The chunk's file name. The module system serves only `client.*.js` siblings. */
export const CHUNK_FILE = "client.rates.js";

/** Rate fields, in the order one route's tuple carries them. */
export const RATE_FIELDS = ["miss", "hit", "write", "out"];

/** A finite non-negative rate, or zero. */
function rate(value) {
  return typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : 0;
}

/**
 * Every route the presets price, as compact tuples.
 *
 * Resolved through the same lookup the Session fold uses, with no overrides, so
 * a pre-filled row starts from exactly what the plugin would have charged.
 *
 * @param options - a catalog table to read instead of the installed one, the
 * route list to price, the currency for entries that name none, and the DeepSeek
 * official card to price that vendor's routes from.
 * @returns `route -> [currency, miss, hit, write, out, peakMiss, peakHit, peakWrite, peakOut]`.
 */
export function presetTable(options = {}) {
  const catalog = options.catalog ?? catalogPresets();
  const lookup = createPriceLookup({
    overrides: {},
    defaultCurrency: options.defaultCurrency,
    catalog,
    // The pre-filled rates have to be the ones the fold would charge, so the
    // table follows whichever official card is in effect.
    officialCard: options.officialCard
  });
  const routes = {};
  for (const route of options.routes ?? presetRoutes()) {
    const cut = route.indexOf("/");
    if (cut <= 0 || cut === route.length - 1) continue;
    const price = lookup(route.slice(0, cut), route.slice(cut + 1));
    if (price === null) continue;
    const base = price.base ?? {};
    const peak = price.peak ?? {};
    routes[route] = [
      price.currency,
      ...RATE_FIELDS.map((field) => rate(base[field])),
      ...RATE_FIELDS.map((field) => rate(peak[field]))
    ];
  }
  return routes;
}

/**
 * The chunk's source text: a module that registers itself with the loader.
 *
 * Deterministic for one table, so a restart with an unchanged catalog does not
 * rewrite the file (and does not move the client entry's revision).
 *
 * @param routes - the table {@link presetTable} returned.
 * @param options - the owning package name and the catalog's generation stamp.
 * @returns JavaScript source a browser can evaluate.
 */
export function ratesChunkSource(routes, options = {}) {
  const id = `${options.packageName}/${CHUNK_FILE}`;
  const generatedAt = typeof options.generatedAt === "number" && Number.isFinite(options.generatedAt)
    ? String(options.generatedAt)
    : "null";
  return [
    "// Generated by dsh-session-cost from the installed model catalog.",
    "// Regenerated by the Host half; not source. Do not edit.",
    "window.__ModuleLoader__.load({",
    `\tid: ${JSON.stringify(id)},`,
    "\tfactory: (require) => {",
    "\t\tvar module = { exports: {} };",
    "\t\tvar exports = module.exports;",
    `\t\texports.generatedAt = ${generatedAt};`,
    `\t\texports.routes = ${JSON.stringify(routes)};`,
    "\t\treturn module.exports;",
    "\t}",
    "});",
    ""
  ].join("\n");
}

/**
 * Materialize the chunk next to `client.js`.
 *
 * Never throws: a plugin installed somewhere read-only simply has no pre-filled
 * table, and the settings page falls back to typing the rates. Nothing on the
 * Session path depends on this.
 *
 * @param options - the `lib/` directory to write into, the owning package name,
 * and the table inputs {@link presetTable} takes.
 * @returns the outcome: whether the file changed, its path, and any failure.
 */
export function materializeRatesChunk(options = {}) {
  const directory = options.directory;
  if (typeof directory !== "string" || directory === "") {
    return { changed: false, path: "", routes: 0, failure: "no directory" };
  }
  const path = join(directory, CHUNK_FILE);
  try {
    const table = options.table ?? presetTable(options);
    const source = ratesChunkSource(table, {
      packageName: options.packageName,
      generatedAt: options.generatedAt ?? catalogGeneratedAt()
    });
    let current = null;
    try {
      current = readFileSync(path, "utf8");
    } catch (_absent) {
      current = null;
    }
    const routes = Object.keys(table).length;
    if (current === source) return { changed: false, path, routes };
    writeFileSync(path, source);
    // Move the client entry's revision so the chunk URL, and the browser cache
    // keyed to it, follow this table. The file's content is untouched on purpose.
    const now = new Date();
    utimesSync(join(directory, options.ownerFile ?? "client.js"), now, now);
    return { changed: true, path, routes };
  } catch (error) {
    return {
      changed: false,
      path,
      routes: 0,
      failure: error instanceof Error ? error.message : String(error)
    };
  }
}
